### ISSUE TITLE
Support multiple ArgoCD instances

### ISSUE THREAD

**Issue by martina-if** [RoadieHQ/backstage-plugin-argo-cd#1]
Originally posted in [backstage#683](https://github.com/backstage/backstage/issues/683#issuecomment-738474982)

>It'd be nice to have support for multiple ArgoCD instances. I know that some large organizations out there swimlane their ArgoCD instances by organization or environment - it'd be nice to be able to collect data from more than a single instance.

**Comment by mcalus3** [comment]
@martina-if Is it the same as #7? Support for displaying multiple ArgoCD applications?

**Comment by muenchdo** [comment]
I think only partially. In the use case described in this ticket, multiple Argo CD "installations" would need to be queried, not sure how this would work with the proxy.
