### ISSUE TITLE
Published Argo CD plugin malformed

### ISSUE THREAD

**Issue by iain-b** [RoadieHQ/backstage-plugin-argo-cd#10]
The dist folder is missing from the published plugin:

https://discord.com/channels/687207715902193673/687207715902193679/799530731692359680

**Comment by mcalus3** [comment]
Published 0.1.3 version with complete files.

Last ArgoCD plugin deploy was done 25 days ago and it wasn't by the automatic workflow so i guess that the workflows are fine and the reason was some manual mistake during publishing by me. Good that now it's automated.
