### ISSUE TITLE
Support linking an AppProject with an entity

### ISSUE THREAD

**Issue by martina-if** [RoadieHQ/backstage-plugin-argo-cd#2]
Originally posted [here](https://github.com/backstage/backstage/issues/683#issuecomment-738474982).

>It'd be nice to be able to associate a catalog entity with an ArgoCD AppProject. One use case could be where a service has multiple environments grouped under a project - it'd be great just to link the project and automatically show the sync status/health of each environment.

**Comment by muenchdo** [comment]
I think this could be quite a simple extension to what I did in #7 by adding a new annotation `argocd-cd/project` and using that to query the apps based on the project. Would be happy to take it 🙂

**Comment by martina-if** [comment]
Hi @muenchdo, yeah, we would be happy to accept PRs for it!

**Comment by mcalus3** [comment]
@muenchdo @martina-if I think #26 implements this feature.
