### ISSUE TITLE
Invalid character in header content ["Cookie"]

### ISSUE THREAD

**Issue by banshee86vr** [RoadieHQ/backstage-plugin-argo-cd#52]
Using the plugin with the latest version of Backstage I'm receiving the error:

`Invalid character in header content ["Cookie"]`

Executing the same call with the GET `applications` API provided by Argo it works settings `Cookie` in the headers with the value `argued.token=...`.

## Expected Behavior

Show the widget details about the application

## Current Behavior

`Error occurred while fetching data. Error: failed to fetch data, status 500:`

## Steps to Reproduce

1. Configure the plugin following official README (https://github.com/RoadieHQ/backstage-plugin-argo-cd/blob/main/README.md)
2. Set value of env var `ARGOCD_AUTH_TOKEN` to `argocd.token=...`

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3):0.3.6
- Backstage version (e.g. 0.1.1-alpha23): 0.7.3
- NodeJS Version (e.g. v12): v14.16.0
- Operating System and Version (e.g. Ubuntu 14.04): MacOS BigSur
- Browser Information (e.g. chrome 85): Chrome + Safari

**Comment by martina-if** [comment]
Hi @banshee86vr , we haven't been able to reproduce this with the latest backstage version. Is it possible that this is a configuration problem and there is some extra character like a new line, for example,  in the token?

**Comment by banshee86vr** [comment]
Hi @martina-if I re-installed all backstage app from scratch and I can't reproduce the error 🤔.
