### ISSUE TITLE
External contribution guidelines

### ISSUE THREAD

**Issue by desktophero** [RoadieHQ/backstage-plugin-argo-cd#58]
👋 

My team is looking to contribute some items to this plugin and wanted to see if there is a current contributing guideline we should follow.

Thanks!

**Comment by dtuite** [comment]
Hi @desktophero . We don't currently have anything, but we should, and I intend to fix this as soon as possible.

We will aim to stick as close as possible to the Backstage contributing guidelines so you can use them as your guide while I create some official ones in this repository.

What are the attributes of a well written contributing guideline that you care most about?

**Comment by dtuite** [comment]
Hi @desktophero. I have tackled this issue in #59 . Please let me know if you feel there is anything missing from that PR.
